import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { renderPdf } from './evidence.js';
import { mkdirSync, rmSync, existsSync, statSync } from 'fs';
import { join } from 'path';

// Mock watsonx to avoid real API calls
vi.mock('../lib/watsonx.js', () => ({
  generateProse: vi.fn(async (section: string) => {
    return `Mock ${section} prose generated by granite-3-8b-instruct for testing.`;
  }),
}));

describe('evidence.renderPdf', () => {
  const testOutputDir = join(process.cwd(), 'compliance/evidence/PR-999');

  beforeEach(() => {
    // Clean up test directory before each test
    if (existsSync(testOutputDir)) {
      rmSync(testOutputDir, { recursive: true, force: true });
    }
  });

  afterEach(() => {
    // Clean up test directory after each test
    if (existsSync(testOutputDir)) {
      rmSync(testOutputDir, { recursive: true, force: true });
    }
  });

  it('generates a valid PDF with all sections', async () => {
    const input = {
      pr_number: 999,
      repo_metadata: {
        repo_name: 'bobguard',
        branch: 'test-branch',
        commit_sha: 'abc123def456',
        author: 'test-author',
      },
      triggered_controls: [
        {
          control_id: '164.312(a)(2)(iv)',
          control_name: 'Encryption and Decryption',
          family: 'Technical Safeguards',
          file: 'src/prisma/schema.prisma',
          line: 34,
          severity: 'block',
          existing_status: 'addressable',
          nprm_status: 'Would become required',
        },
      ],
      control_map_md: '| Control | File | Severity |\n|---|---|---|\n| 164.312(a)(2)(iv) | src/prisma/schema.prisma:34 | block |',
      threat_delta_md: 'New PHI fields stored unencrypted in database.',
      test_evidence_json: {
        phi_encryption_roundtrip: {
          status: 'pass',
          duration_ms: 14,
        },
      },
      nprm_narrative: 'This control is affected by the 2024 NPRM.',
    };

    const result = await renderPdf(input);

    // Verify output structure
    expect(result).toHaveProperty('pdf_path');
    expect(result).toHaveProperty('page_count');
    expect(result).toHaveProperty('watsonx_used');

    // Verify PDF was created
    expect(existsSync(result.pdf_path)).toBe(true);

    // Verify PDF has reasonable size (> 5KB)
    const stats = statSync(result.pdf_path);
    expect(stats.size).toBeGreaterThan(5000);

    // Verify page count is reasonable
    expect(result.page_count).toBeGreaterThanOrEqual(2);

    // Verify watsonx was used (mocked)
    expect(result.watsonx_used).toBe(true);
  }, 30000); // 30s timeout for Puppeteer

  it('handles multiple triggered controls', async () => {
    const input = {
      pr_number: 999,
      repo_metadata: {
        repo_name: 'bobguard',
        branch: 'test-branch',
        commit_sha: 'abc123',
        author: 'test-author',
      },
      triggered_controls: [
        {
          control_id: '164.312(a)(2)(iv)',
          control_name: 'Encryption',
          severity: 'block',
        },
        {
          control_id: '164.312(b)',
          control_name: 'Audit Controls',
          severity: 'block',
        },
        {
          control_id: '164.312(d)',
          control_name: 'Person or Entity Authentication',
          severity: 'warn',
        },
      ],
      control_map_md: 'Multiple controls triggered',
      threat_delta_md: 'Multiple vulnerabilities',
      test_evidence_json: {},
      nprm_narrative: 'Multiple controls affected',
    };

    const result = await renderPdf(input);

    expect(existsSync(result.pdf_path)).toBe(true);
    expect(result.page_count).toBeGreaterThanOrEqual(7);
  }, 30000);

  it('creates output directory if it does not exist', async () => {
    const input = {
      pr_number: 999,
      repo_metadata: {
        repo_name: 'bobguard',
        branch: 'test',
        commit_sha: 'test',
        author: 'test',
      },
      triggered_controls: [],
      control_map_md: '',
      threat_delta_md: '',
      test_evidence_json: {},
      nprm_narrative: '',
    };

    // Ensure directory doesn't exist
    if (existsSync(testOutputDir)) {
      rmSync(testOutputDir, { recursive: true, force: true });
    }

    const result = await renderPdf(input);

    // Verify directory was created
    expect(existsSync(testOutputDir)).toBe(true);
    expect(existsSync(result.pdf_path)).toBe(true);
  }, 30000);

  it('sets status to blocked when block-severity controls present', async () => {
    const input = {
      pr_number: 999,
      repo_metadata: {
        repo_name: 'bobguard',
        branch: 'test',
        commit_sha: 'test',
        author: 'test',
      },
      triggered_controls: [
        {
          control_id: '164.312(a)(2)(iv)',
          severity: 'block',
        },
      ],
      control_map_md: '',
      threat_delta_md: '',
      test_evidence_json: {},
      nprm_narrative: '',
    };

    const result = await renderPdf(input);

    // PDF should be generated successfully
    expect(existsSync(result.pdf_path)).toBe(true);
    
    // Status should be reflected in the PDF (we can't easily parse PDF content,
    // but we verify the file was created with the correct logic)
    expect(result.pdf_path).toContain('PR-999');
  }, 30000);

  it('includes NPRM control blocks when nprm_status provided', async () => {
    const input = {
      pr_number: 999,
      repo_metadata: {
        repo_name: 'bobguard',
        branch: 'test',
        commit_sha: 'test',
        author: 'test',
      },
      triggered_controls: [
        {
          control_id: '164.312(a)(2)(iv)',
          control_name: 'Encryption',
          severity: 'block',
          existing_status: 'addressable',
          nprm_status: 'Would become required under 2024 NPRM',
        },
      ],
      control_map_md: '',
      threat_delta_md: '',
      test_evidence_json: {},
      nprm_narrative: 'Forward-compatibility analysis',
    };

    const result = await renderPdf(input);

    expect(existsSync(result.pdf_path)).toBe(true);
    expect(result.watsonx_used).toBe(true);
  }, 30000);
});

// Made with Bob
